name: Ensure changeset exists

on:
  pull_request:
    branches: [main]

jobs:
  changeset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Get original package info
        id: originalPackageInfo
        uses: gregoranders/nodejs-project-info@v0.0.10
      - name: Install dependencies
        uses: bahmutov/npm-install@v1.1.0
      - name: Add Changeset
        uses: ianwalter/add-changeset@v1.0.8
        with:
          type: patch
      - name: Apply changeset
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: changeset version
          auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Get updated package info
        id: updatedPackageInfo
        uses: gregoranders/nodejs-project-info@v0.0.10
      - name: Ensure package.json has been updated
        uses: actions/github-script@v2
        if: ${{ steps.originalPackageInfo.outputs.version == steps.updatedPackageInfo.outputs.version }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ This PR is missing a changeset!'
            })
