name: Publish Github Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Release
        uses: anton-yurchenko/git-release@v3.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: 'false'
          PRE_RELEASE: 'false'
          CHANGELOG_FILE: 'CHANGELOG.md'
          ALLOW_EMPTY_CHANGELOG: 'false'
          ALLOW_TAG_PREFIX: 'true'
        with:
          args: |
            dist/*
