name: Run linter

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        uses: bahmutov/npm-install@v1.1.0
      - name: Run linter
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: lint
          auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
