name: Prettify code

on:
  pull_request:
    branches: [main]

jobs:
  prettify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run Prettier Action
        uses: creyD/prettier_action@v3.0
        with:
          commit_message: ':art: Prettify code!'
          prettier_options: --write **/*
